# The status generator command.
# Optional: with no status generator the bar will display only tags and layout name.
command = "i3status-rs"

# Colors
background = "#282c34ff"
color = "#979eabff"
separator = "#282c34ff"
tag_fg = "#979eabff"
tag_bg = "#393e48ff"
tag_focused_fg = "#282c34ff"
tag_focused_bg = "#61afefff"
tag_urgent_fg = "#282828ff"
tag_urgent_bg = "#cc241dff"
tag_inactive_fg = "#d79921ff"
tag_inactive_bg = "#282828ff"

# The font and various sizes
font = "Hack Nerd Font 12"
height = 20
separator_width = 0
tags_r = 10
blocks_r = 10
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
tags_padding = 25.0
tags_margin = 0.0
blocks_overlap = 0.0

# Misc
position = "top" # either "top" or "bottom"
layer = "top" # one of "top", "overlay", "bottom" or "background"
hide_inactive_tags = true
invert_touchpad_scrolling = false
show_tags = true
show_layout_name = true
blend = true # whether tags/blocks colors should blend with bar's background
show_mode = true

# WM-specific options
[wm.river]
max_tag = 9 # Show only the first nine tags

# Per output overrides
# [output.your-output-name]
# right now only "enable" option is available
# enable = false
#
# You can have any number of overrides
# [output.eDP-1]
# enable = false
